# Generated by Django 5.2.7 on 2025-11-21 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMessageTemplate',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='模板code')),
                ('title', models.CharField(max_length=100, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息模板内容')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
                'db_table': 'tb_message_template',
            },
        ),
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('msg_chanel', models.IntegerField(choices=[(1, '系统通知'), (2, '平台公告')], default=1, verbose_name='消息渠道')),
                ('public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('msg_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='消息标题')),
                ('msg_content', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('to_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='跳转路径')),
                ('status', models.BooleanField(default=True, verbose_name='通知状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('msg_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leemessages.mymessagetemplate', verbose_name='消息类型')),
            ],
            options={
                'verbose_name': '消息中心',
                'verbose_name_plural': '消息中心',
                'db_table': 'tb_message',
            },
        ),
        migrations.CreateModel(
            name='MyMessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leemessages.mymessage', verbose_name='消息ID')),
                ('revuserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagerevuserid', to=settings.AUTH_USER_MODEL, verbose_name='接收者用户ID')),
                ('senduserid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagesenduserid', to=settings.AUTH_USER_MODEL, verbose_name='发送者用户ID')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
                'db_table': 'tb_message_user',
            },
        ),
    ]
